fix: start to fix statefulset unit test
Signed-off-by: disaster37 <linuxworkgroup@hotmail.com>

diff --git a/controllers/elasticsearch/testdata/statefullset-all.yml b/controllers/elasticsearch/testdata/statefullset-all.yml
--- a/controllers/elasticsearch/testdata/statefullset-all.yml
+++ b/controllers/elasticsearch/testdata/statefullset-all.yml
@@ -22,6 +22,7 @@ spec:
       labels:
         cluster: test
         nodeGroup: all
+        elasticsearch.k8s.webcenter.fr: "true"
       annotations:
         elasticsearch.k8s.webcenter.fr/checksum-elasticsearch.yml: "2a0a8650b1d7a5f22e433877319457161489869868b894d448b2616477b521aa"
       name: test-all-es
@@ -37,27 +38,24 @@ spec:
                 topologyKey: kubernetes.io/hostname
               weight: 10
       containers:
-      - command:
-        - sh
-        - -c
-        - |
-          #!/usr/bin/env bash
-          set -euo pipefail
-
-          bash elasticsearch-docker-entrypoint.sh
-        env:
-        - name: node.master
-          value: "true"
-        - name: node.data
-          value: "true"
-        - name: node.ingest
-          value: "true"
-        - name: node.ml
-          value: "false"
-        - name: node.remote_cluster_client
-          value: "false"
-        - name: node.transform
-          value: "false"
+      - env:
+        - name: network.publish_host
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: status.podIP
+        - name: node.attr.node_name
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: spec.nodeName
+        - name: node.name
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: metadata.name
+        - name: node.roles
+          value: master, data, ingest
         - name: ELASTIC_PASSWORD
           valueFrom:
             secretKeyRef:
@@ -93,10 +91,12 @@ spec:
           value: test
         - name: network.host
           value: 0.0.0.0
-        - name: bootstrap.memory_lock
-          value: "true"
         - name: discovery.type
           value: single-node
+        - name: PROBE_WAIT_STATUS
+          value: green
+        - name: PROBE_SCHEME
+          value: https
         image: docker.elastic.co/elasticsearch/elasticsearch:latest
         livenessProbe:
           failureThreshold: 10
@@ -117,8 +117,47 @@ spec:
           failureThreshold: 3
           periodSeconds: 30
           successThreshold: 1
-          tcpSocket:
-            port: 9200
+          exec:
+            command:
+              - /bin/bash
+              - -c
+              - |
+                  #!/usr/bin/env bash
+                  set -euo pipefail
+
+                  # Implementation based on Elasticsearch helm template
+
+                  export NSS_SDB_USE_CACHE=no
+
+                  STARTER_FILE=/tmp/.es_starter_file
+                  if [ -f ${STARTER_FILE} ]; then
+                    HTTP_CODE=$(curl --output /dev/null -k -XGET -s -w '%{http_code}' -u elastic:${ELASTIC_PASSWORD} ${PROBE_SCHEME}://127.0.0.1:9200/)
+                    RC=$?
+                    if [[ ${RC} -ne 0 ]]; then
+                      echo "Failed to get Elasticsearch API"
+                      exit ${RC}
+                    fi
+                    if [[ ${HTTP_CODE} == "200" ]]; then
+                      exit 0
+                    else
+                      echo "Elasticsearch API return code ${HTTP_CODE}
+                      exit 1
+                    fi
+                  else
+                    HTTP_CODE=$(curl --output /dev/null -k -XGET -s -w '%{http_code}' -u elastic:${ELASTIC_PASSWORD} --fail ${PROBE_SCHEME}://127.0.0.1:9200/_cluster/health?wait_for_status=${PROBE_WAIT_STATUS}&timeout=1s)
+                    RC=$?
+                    if [[ ${RC} -ne 0 ]]; then
+                      echo "Failed to get Elasticsearch API"
+                      exit ${RC}
+                    fi
+                    if [[ ${HTTP_CODE} == "200" ]]; then
+                      touch ${STARTER_FILE}
+                      exit 0
+                    else
+                      echo "Elasticsearch API return code ${HTTP_CODE}
+                      exit 1
+                    fi
+                  fi
           timeoutSeconds: 5
         securityContext:
           capabilities:
@@ -135,15 +174,8 @@ spec:
             port: 9200
           timeoutSeconds: 5
         volumeMounts:
-        - mountPath: /usr/share/elasticsearch/config/certs/node
-          name: node-tls
-        - mountPath: /usr/share/elasticsearch/config/certs/api
-          name: api-tls
-        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
-          name: elasticsearch-config
-          subPath: elasticsearch.yml
-        - mountPath: /mnt/keystore
-          name: keystore
+        - mountPath: /usr/share/elasticsearch/config
+          name: config
       initContainers:
       - command:
         - sysctl
@@ -153,6 +185,84 @@ spec:
         name: configure-sysctl
         securityContext:
           privileged: true
+          runAsUser: 0
+      - command:
+        - /bin/bash
+        - -c
+        - |
+            #!/usr/bin/env bash
+            set -euo pipefail
+            
+            # Move original config
+            echo "Move original elasticsearch configs"
+            cp -a /usr/share/elasticsearch/config/* /mnt/config/
+
+            # Move configmaps
+            if [ -d /mnt/configmap ]; then
+              echo "Move custom configs"
+              cp -rf /mnt/configmap/* /mnt/config/
+            fi
+
+            # Move certificates
+            echo "Move cerficates"
+            mkdir -p /mnt/config/api-cert /mnt/config/transport-cert
+            cp /mnt/certs/api/* /mnt/config/api-cert/
+            cp /mnt/certs/node/ca.crt /mnt/config/transport-cert/
+            cp /mnt/certs/node/${POD_NAME}.crt /mnt/config/transport-cert/
+            cp /mnt/certs/node/${POD_NAME}.key /mnt/config/transport-cert/
+
+            # Move keystore
+            if [ -f /mnt/keystore/elasticsearch.keystore ]; then
+              echo "Move keystore"
+              cp /mnt/keystore/elasticsearch.keystore /mnt/config
+            fi
+
+            # Set right
+            echo "Set right"
+            chown -R elasticsearch:elasticsearch /mnt/config
+            if [ -d /mnt/data ]; then
+              chown -v elasticsearch:elasticsearch /mnt/data
+            fi
+
+
+            if [ -d /mnt/plugins ]; then
+              cp -a /usr/share/elasticsearch/plugins/* /mnt/plugins/
+            fi
+
+        image: docker.elastic.co/elasticsearch/elasticsearch:latest
+        name: init-filesystem
+        env:
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: metadata.name
+        - name: NODE_NAME
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: spec.nodeName
+        - name: POD_IP
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: status.podIP
+        - name: NAMESPACE
+          valueFrom:
+            fieldRef:
+              apiVersion: v1
+              fieldPath: metadata.namespace
+        volumeMounts:
+          - name: config
+            mountPath: /mnt/config
+          - name: node-tls
+            mountPath: /mnt/certs/node
+          - name: api-tls
+            mountPath: /mnt/certs/api
+          - name: elasticsearch-config
+            mountPath: /mnt/configmap/elasticsearch.yml
+            subPath: elasticsearch.yml
+        securityContext:
           runAsUser: 0
       securityContext:
         fsGroup: 1000
@@ -168,4 +278,8 @@ spec:
           name: test-all-config-es
         name: elasticsearch-config
       - name: keystore
+        emptyDir: {}
+      - name: config
+        emptyDir: {}
+      - name: plugin
         emptyDir: {}
